### ISSUE TITLE
LDAP integration ?

### ISSUE THREAD

**Issue by SeasLiV** [arjunbalussery/gateway#2]
Hello,

I've a question,
I was thinking about adding my LDAP server to this microservices and make it work with the JWT tokens.
Do you know if it's possible using this example ?

Regards,
Rémy

**Comment by ILyaCyclone** [comment]
Authentication source doesn't really matter, be it a regular database or LDAP. You need to configure your AuthenticationManager properly, the rest of the process can stay the same.

**Comment by SeasLiV** [comment]
Hello,
Yes, I've find the solution few month ago.
Still, I will post my configuration here, it can help people.

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth
                .ldapAuthentication()
                .contextSource()
                .url(ldapUrls + ldapBaseDn)
                .managerDn(ldapSecurityPrincipal)
                .managerPassword(ldapPrincipalPassword)
                .and()
                .userSearchFilter(ldapFilter);
    }

Regards
